# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    continue-on-error: ${{ (matrix.rust == 'beta') || (matrix.rust == 'nightly') }}

    strategy:
      fail-fast: false
      matrix:
        rust: [
          1.67.0,
          1.68.0,
          1.69.0,
          1.70.0,
          1.71.0,
          stable,
          beta,
          nightly
        ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Install libs
        run: >-
          sudo apt-get update &&
          sudo apt-get install libasound2-dev libavcodec-dev
          libavformat-dev libavutil-dev libavdevice-dev libavfilter-dev
          libpostproc-dev libswscale-dev -y

      - name: Setup FFmpeg
        uses: Iamshankhadeep/setup-ffmpeg@v1.2
        with:
          version: "5.0"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          default: true

      - name: Run cargo test
        run: cargo test

  fmt:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: rustfmt

      - name: Show version
        run: cargo fmt --version

      - name: Run cargo fmt
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install libs
        run: >-
          sudo apt-get update &&
          sudo apt-get install libasound2-dev libavcodec-dev
          libavformat-dev libavutil-dev libavdevice-dev libavfilter-dev
          libpostproc-dev libswscale-dev -y

      - name: Install Rust with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: clippy

      - name: Run cargo clippy
        run: cargo clippy 2>&1 | tee ./clippy.out && ! grep -qe "error:\|warning:" ./clippy.out

  tarpaulin:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install libs
        run: >-
          sudo apt-get update &&
          sudo apt-get install libasound2-dev libavcodec-dev
          libavformat-dev libavutil-dev libavdevice-dev libavfilter-dev
          libpostproc-dev libswscale-dev -y

      - name: Setup FFmpeg
        uses: Iamshankhadeep/setup-ffmpeg@v1.2
        with:
          version: "5.0"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin --force
        env:
          RUSTFLAGS: '--cfg procmacro2_semver_exempt'

      - name: Run cargo-tarpaulin
        run: cargo tarpaulin -v --ciserver travis-ci --coveralls $GITHUB_JOB

